    http_proxy: ""
    nicos_repo: "https://forge.frm2.tum.de/review/frm2/nicos/nicos-core"
    nicos_version: "HEAD"
    nicos_refspec: "HEAD"
    nicos_src_dir: "/opt/nicos-core"
    nicos_inst_dir: "/opt/nicos"
    nicos_data_dir: "/opt/nicos-data"
    nicos_facility: "{{ facility | default('demo') }}"
    nicos_instrument: "{{ instrument | default('demo') }}"
    
