---

- hosts: "{{ variable_host | default('localhost') }}"

  tasks:
    - include: "tasks/download-nicos.yml"

    - include: "tasks/{{ ansible_os_family }}-packages.yml"

    - include: "tasks/install-python-packages.yml"

    - name: make sure that the group nicos exists
      become: yes
      group:
        name: nicos
        state: present

    - name: make sure that the user nicos exists
      become: yes
      user:
        name: '{{ nicos_username }}'
        uid: 1040
        group: '{{ nicos_usergroup }}'

    - name: install nicos
      become: yes
      make:
        chdir: '{{ nicos_src_dir }}'
        target: install
        params:
          PREFIX: '{{ nicos_inst_dir}}'

    - name: make sure that the data directory exists
      become: yes
      file:
        path: '{{ nicos_data_dir }}'
        state: directory
        owner: '{{ nicos_username }}'
        group: '{{ nicos_usergroup }}'
        mode: 0755

    - name: copy the nicos.conf file
      become: yes
      template:
        src: nicos.conf.j2
        dest: '{{ nicos_inst_dir }}/nicos.conf'
        force: yes

    - name: make sure that correct user owns the nicos installation dir
      become: yes
      file:
        path: '{{ nicos_inst_dir }}'
        owner: '{{ nicos_username }}'
        group: '{{ nicos_usergroup }}'

    - name: make sure that the service file is installed
      become: yes
      file:
        src: '{{ nicos_inst_dir }}/etc/nicos-system'
        dest: '/etc/init.d/nicos-system'
        state: link

    - include: "tasks/{{ ansible_os_family }}-install-service.yml"

    - name: copy the nicos env file
      become: yes
      copy:
        src: nicos_env.sh
        dest: /etc/profile.d/nicos_env.sh
        force: yes

    - name: create a link for nicos-gui
      become: yes
      file:
        src: "{{ nicos_inst_dir }}/bin/nicos-gui"
        dest: /usr/local/bin/nicos-gui
        state: link
        force: yes
