---

- hosts: nicos
  vars:
    http_proxy: ""
    nicos_repo: "https://forge.frm2.tum.de/review/frm2/nicos/nicos-core"
    nicos_version: "HEAD"
    nicos_refspec: "HEAD"
    nicos_src_dir: "/opt/nicos-core"
    nicos_inst_dir: "/opt/nicos"
    nicos_data_dir: "/opt/nicos-data"
    nicos_facility: "nicos_demo"
    nicos_instrument: "demo"

  tasks:
    - name: cleanup the current src dir
      become: yes
      file:
        path: '{{nicos_src_dir}}'
        state: absent

    - name: make sure nicos is checked out
      become: yes
      git:
        repo: '{{ nicos_repo }}'
        dest: '{{ nicos_src_dir }}'
        version: '{{ nicos_version }}'
        refspec: '{{ nicos_refspec }}'
        force: yes

    - include: "tasks/{{ ansible_os_family }}-packages.yml"

    - name: make sure that the group nicos exists
      become: yes
      group:
        name: nicos
        state: present

    - name: make sure that the user nicos exists
      become: yes
      user:
        name: nicos
        uid: 1040
        group: nicos

    - name: install nicos
      become: yes
      make:
        chdir: '{{ nicos_src_dir }}'
        target: install
        params:
          PREFIX: '{{ nicos_inst_dir}}'

    - name: make sure that the data directory exists
      become: yes
      file:
        path: '{{ nicos_data_dir }}'
        state: directory
        owner: nicos
        group: nicos
        mode: 0755

    - name: copy the nicos.conf file
      become: yes
      template:
        src: nicos.conf.j2
        dest: '{{ nicos_inst_dir }}/nicos.conf'
        force: yes

    - name: make sure that user nicos owns the nicos installation dir
      become: yes
      file:
        path: '{{ nicos_inst_dir }}'
        owner: nicos
        group: nicos

    - name: make sure that the service file is installed
      become: yes
      file:
        src: '{{ nicos_inst_dir }}/etc/nicos-system'
        dest: '/etc/init.d/nicos-system'
        state: link

    - include: "tasks/{{ ansible_os_family }}-install-service.yml"

    - name: copy the nicos env file
      become: yes
      copy:
        src: nicos_env.sh
        dest: /etc/profile.d/nicos_env.sh
        force: yes

    - name: create a link for nicos-gui
      become: yes
      file:
        src: "{{ nicos_inst_dir }}/bin/nicos-gui"
        dest: /usr/local/bin/nicos-gui
        state: link
        force: yes
