# Based on informationfrom https://forge.frm2.tum.de/nicos/doc/nicos-master/install/
---

- name: be sure required packages are installed
  become: yes
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - python
    - python-dev
    - python-pip
    - python-setuptools
    - gnuplot
    - python-mysql.connector
    - python-qt4
    - python-qscintilla2
    - python-sip-dev
    - python-qt4-dev

- name: install general python packages
  become : yes
  pip:
    name: "{{item}}"
    state: forcereinstall
    extra_args: "--proxy={{ http_proxy }} --ignore-installed"
  with_items:
    - pip
    - setuptools
    - kafka-python
    - pyepics
    - flatbuffers

- name: install python requirements
  become: yes
  pip:
    state: latest
    requirements: '{{ nicos_src_dir }}/requirements.txt'
    extra_args: "--proxy={{ http_proxy }} --ignore-installed"

- name: install python dev requirements
  become: yes
  pip:
    state: latest
    requirements: '{{ nicos_src_dir }}/requirements-dev.txt'
    extra_args: "--proxy={{ http_proxy }} --ignore-installed"
