---

- name: cleanup the current src dir
  become: yes
  file:
    path: '{{nicos_src_dir}}'
    state: absent

- name: make sure nicos is checked out
  become: yes
  git:
    repo: '{{ nicos_repo }}'
    dest: '{{ nicos_src_dir }}'
    version: '{{ nicos_version }}'
    refspec: '{{ nicos_refspec }}'
    force: yes
