---

- name: cleanup the current src dir
  become: yes
  file:
    path: '{{nicos_src_dir}}'
    state: absent

- name: clone nicos
  become: yes
  git:
    repo: '{{ nicos_repo }}'
    dest: '{{ nicos_src_dir }}'
    version: '{{ nicos_version }}'
    refspec: '{{ nicos_refspec }}'
    force: yes
  when: nicos_download == 'no'

- name: download nicos
  become: yes
  unarchive:
    src: "http://project.esss.dk/owncloud/index.php/s/ClJ6YpCjH1IIiAr/download"
    dest: '/opt'
    force: yes
    remote_src: yes
  when: nicos_download == 'yes'
